// export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
// export const DECLINE_REQUEST = 'DECLINE_REQUEST';
// export const MARK_AS_COLLECTED = 'MARK_AS_COLLECTED';
// export const SEND_REQUEST = 'SEND_REQUEST';
// export const NOTIFY_RECIPIENT = 'NOTIFY_RECIPIENT';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
export const MARK_AS_COLLECTED = 'MARK_AS_COLLECTED';
